steps:
  - label: ":clojure: build"
    command:
      - ".buildkite/script.sh"
    plugins:
      docker#v1.3.0:
        image: "clojure"
    branches: "feature/* release/* hotfix/*"


  - wait

  - label: ":docker: build"
    command: ".buildkite/build.sh"

    #- wait: ~
    #continue_on_failure: true

    #- label: ":console: push logs"
    #command: .buildkite/pushlogs.sh "@denis.khoshaba"
