steps:
  - label: ":clojure:"
    command:
      - ".buildkite/script.sh"
    plugins:
      docker#v1.3.0:
        image: "clojure"
        user: "1000"
    branches: "feature/* release/* hotfix/*"

  - wait

  - label: ":console:"
    command: "buildkite-agent artifact download target/uberjar/*.jar --step ${BUILDKITE_JOB_ID} --build ${BUILDKITE_BUILD_ID} && ls -la"

    #- wait: ~
    #continue_on_failure: true

    #- label: ":console: push logs"
    #command: .buildkite/pushlogs.sh "@denis.khoshaba"
