steps:
  - label: ":clojure:"
    command:
      - ".buildkite/script.sh"
    plugins:
      docker#v1.3.0:
        image: "clojure"
    branches: "feature/* release/* hotfix/*"

  - wait

  - label: ":console:"
    command: "buildkite-agent artifact download target/uberjar/*.jar ./ --step ':clojure:' --build ${BUILDKITE_BUILD_ID} && ./scripts/docker/dockerize.sh"

    #- wait: ~
    #continue_on_failure: true

    #- label: ":console: push logs"
    #command: .buildkite/pushlogs.sh "@denis.khoshaba"
